---
title: "TF array activity plotting"
author: "Max Trauernicht"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
  #   toc: true
  #   toc_float: true
  #   code_folding: show
  # editor_options:
  #   chunk_output_type: console
---

*knitr document van Steensel lab*

# TF array activity plotting

## Introduction
I received sequencing data from TF arrays that consist of 5 different TF reporters. I want to analyze here if the measured barcode counts make any sense. 

```{r setup, out.width= "80%", fig.align= "center", echo=FALSE, warning= FALSE, message=FALSE}
# Path, Libraries, Parameters and Useful Functions
knitr::opts_chunk$set(echo = TRUE)
StartTime <-Sys.time()

# 8-digit Date tag:
Date <- substr(gsub("-","",Sys.time()),1,8) 
# libraries:
library(blogdown)
library(ggplot2)
library(data.table)
library(dplyr)
```


```{r, out.width= "80%", fig.align= "center", echo=FALSE, warning= FALSE, message=FALSE}
# Custom functions
SetFileName <- function(filename, initials) {
  # Set filename with extension and initials to make filename with date integrated.
  filename <- substitute(filename)
  initials <- substitute(initials)
  filename <- paste0(initials, Date, filename)
  filename
}
```



# Import sequencing data 
```{r}
# Import barcode counts per condition - gcf6413
bc_files = list.files('/DATA/usr/m.trauernicht/projects/TF_array/data/gcf6413_TFarrayseq/results/',
                       full.names=T, patter='*_counts.tsv')
bc_list <- lapply(bc_files, fread, header = FALSE)
names(bc_list)<- gsub('.*//6413_[0-9]{1,2}_(.*?)_[CGAT]{6}.*_counts.tsv', 
                                    '\\1', 
                                    bc_files)


# Import barcode annotation
bc_annotation <- read.csv2("~/projects/TF_array/data/gcf6413_TFarrayseq/TF_barcode_association.csv")
```

# Filter sequencing data
```{r}
# Generate long dfs
for (i in 1:length(bc_list)) {
  if (i == 1) {
  bc_df <- data.frame(bc_list[i])
  bc_df[3] <- names(bc_list[i])
  names(bc_df) <- c("barcode", "count", "name")
  bc_df <- reshape2::dcast(bc_df, barcode ~ name, value.var = "count")
  }
  else {
  bc_df_i <- data.frame(bc_list[i])
  bc_df_i[3] <- names(bc_list[i])
  names(bc_df_i) <- c("barcode", "count", "name")
  bc_df_i <- reshape2::dcast(bc_df_i, barcode ~ name, value.var = "count")
  bc_df <- merge(bc_df, bc_df_i, all = T)
  }
}

# Only keep designed barcodes
bc_df <- bc_df[bc_df$barcode %in% bc_annotation$barcode,]

# Add TF data
bc_df <- merge(bc_df, bc_annotation)


# Convert to long df
bc_df_long <- melt(bc_df, id.vars = c("barcode", "TF"),
              variable.name = "condition", value.name = "counts", as.is = T)

# Compute reads per million to estimate the relative counts in their respective sample
for (i in unique(bc_df_long$condition)) {
  bc_df_long$rpm[bc_df_long$condition == i] <- (bc_df_long$counts[bc_df_long$condition == i] + 1) / # Adds a pseudocount of 1
    sum(bc_df_long$counts[bc_df_long$condition == i]) *1e6
}

# Normalize counts by dividing by pDNA counts
bc_df_long$plasmid <- gsub("(^pMT[0-9]{2}).*", "\\1", bc_df_long$condition)
bc_df_long$condition <- gsub("^pMT[0-9]{2}_(.*)", "\\1", bc_df_long$condition)

pDNA_df <- bc_df_long[-grep(".*_r[1,2]", bc_df_long$condition),] %>%
  select(barcode, plasmid, 'pDNA' = rpm) 

bc_df_long <- merge(bc_df_long, pDNA_df, all = T)
bc_df_long$activity <- bc_df_long$rpm / bc_df_long$pDNA
bc_df_long<- bc_df_long[-grep("^pMT[0-9]{2}", bc_df_long$condition),]

background <- bc_df_long %>%
  filter(TF == "Random") %>%
  select(plasmid, condition, 'background' = activity) %>%
  mutate(background = ave(background, condition, plasmid, FUN = function(x) mean(x))) %>%
  unique()

bc_df_long <- merge(bc_df_long, background, by = c("plasmid", "condition"), all = T)
bc_df_long$activity_norm <- bc_df_long$activity / bc_df_long$background

bc_df_long <- bc_df_long %>%
  select(plasmid, TF, condition, activity_norm, activity) %>%
  unique()
```



# Plotting tf activity heatmaps
```{r, out.width= "80%", fig.align= "center", echo=FALSE, warning= FALSE, message=FALSE}
# Plot all data
bc_df_long$TF <- factor(bc_df_long$TF, levels = c("NFE2L2", "TCF7L2", "STAT3", "Random", "NFYA"))

ggplot(bc_df_long, 
       aes(x = TF, y = activity)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  facet_grid(plasmid ~ condition) +
  coord_flip()


ggplot(bc_df_long %>%
         mutate(rep = gsub(".*(r[1,2]$)", "\\1",condition),
                condition = gsub("_r[1,2]$", "", condition),
                activity_norm = ave(activity_norm, condition, TF, plasmid, FUN = function(x) mean(x))), 
       aes(x = TF, y = log2(activity_norm), fill = log2(activity_norm))) +
  geom_bar(stat = "identity") +
  theme_bw() +
  scale_fill_gradient2(midpoint = mean(log2(bc_df_long$activity_norm)), low = "blue", mid = "grey",
                            high = "red", space = "Lab" ) +
  facet_grid(plasmid ~ condition) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  ylab("log2 activity relative to random reporter") +
  coord_flip()


# Include data from previous MPRA
# Specify the chosen reporters
selection_df <- data.frame(TF = c("Random1","Stat3","Tcf7l2","Nfya", "Nfe2l2"),
                           Spacing = c("5bp", "10bp", "5bp", "5bp", "5bp"),
                           Distance = c("10bp", "10bp", "10bp", "10bp", "10bp"),
                           Promoter = c("mCMV", "mCMV", "mCMV", "mCMV", "mCMV"),
                           Background = c("1", "3", "3", "2", "3"))
selection_df <- selection_df %>%
  mutate(reporter_id = paste(TF, Spacing, Distance, Promoter, Background, sep = "_"))


# Import MPRA data
cDNA_df <- read.csv("/DATA/shared/projects/TF_REPORTERS/SuRE-TF/data/gcf6139_stimulation-2/results/mt20201209_reporter_activity_filt.csv", header = T)
cDNA_df_1 <- read.csv("/DATA/shared/projects/TF_REPORTERS/SuRE-TF/data/gcf5927_stimulation-1/results/mt20201209_reporter_activity_filt.csv", header = T)
cDNA_df_1 <- cDNA_df_1 %>% setnames(c("background", "promoter", 
                                      "spacing", "distance", "bc.number"),
                                    c("Background", "Promoter", "Spacing", 
                                      "Distance", "Barcode"))
cDNA_df <- rbind(cDNA_df, cDNA_df_1)


cDNA_df_filt <- cDNA_df %>%
  mutate(reporter_id = paste(TF, Spacing, Distance, Promoter, Background, sep = "_")) %>%
  filter(reporter_id %in% selection_df$reporter_id,
         Barcode == 4) %>%
  select(condition, TF, 'activity' = reporter_activity) %>%
  mutate(plasmid = "MPRA") %>%
  filter(condition %in% c("HQ", "2i_pos_LIF", "2i_neg_LIF", "LIF_pos_PD")) %>%
  unique()

cDNA_df_filt$condition[cDNA_df_filt$condition == "LIF_pos_PD"] <- "LIF_PD"
cDNA_df_filt$condition[cDNA_df_filt$condition == "2i_pos_LIF"] <- "2i_LIF"
cDNA_df_filt$condition[cDNA_df_filt$condition == "2i_neg_LIF"] <- "2i"
cDNA_df_filt$TF <- toupper(cDNA_df_filt$TF)
cDNA_df_filt$TF[cDNA_df_filt$TF == "RANDOM1"] <- "Random"


background <- cDNA_df_filt %>%
  filter(TF == "Random") %>%
  select(plasmid, condition, 'background' = activity) %>%
  mutate(background = ave(background, condition, plasmid, FUN = function(x) mean(x))) %>%
  unique()

cDNA_df_filt <- merge(cDNA_df_filt, background, all = T)
cDNA_df_filt$activity_norm <- cDNA_df_filt$activity / cDNA_df_filt$background

cDNA_df_filt <- cDNA_df_filt %>%
  select(-background)

bc_df_long <- rbind(bc_df_long, cDNA_df_filt)

bc_df_long <- bc_df_long %>%
         mutate(condition = gsub("_r[1,2]$", "", condition),
                activity_norm = ave(activity_norm, condition, TF, plasmid, FUN = function(x) mean(x))) %>%
  select(plasmid, TF, condition, activity_norm) %>%
  mutate(activity_norm = log2(activity_norm)) %>%
  unique()

ggplot(bc_df_long, 
       aes(x = TF, y = activity_norm, fill = activity_norm)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  scale_fill_gradient2(midpoint = mean(bc_df_long$activity_norm), low = "blue", mid = "grey",
                            high = "red", space = "Lab" ) +
  facet_grid(plasmid ~ condition) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  ylab("log2 activity relative to random reporter") +
  coord_flip()




```


# Import TIDE data and overlay
```{r, out.width= "80%", fig.align= "center", echo=FALSE, warning= FALSE, message=FALSE}
```


# Session Info
```{r}
paste("Run time: ",format(Sys.time()-StartTime))
getwd()
date()
sessionInfo()
```

